apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  clusterIP: 10.96.0.2
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-deployment
 labels:
   role: app
spec:
 replicas: 1
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: "blaqprodukt/alienworkshop:flaskapi"
     - name: web
       image: "blaqprodukt/alienworkshop:frontend"
       env:
       - name: 'NAME'
         value: 'Walter Khumalo'
